
 export const baseurl= "http://localhost:5000/api/Account/"
// export const baseurl = "http://usermanagement-api.portal.nastechltd.co/api/Account/"
// export const baseurlAttendance = "http://attendancemanagement-api.portal.nastechltd.co/api/Attendance/"
export const baseurlAttendance = "http://localhost:5002/api/Attendance/"
export const baseurlSalary = "http://localhost:5006/api/Salary/"
export const baseurlInventory = "http://localhost:5008/api/Inventory/"
export const baseurlInventoryRequest = "http://localhost:5008/api/InventoryRequest/"
export const baseurlProject = "http://localhost:5010/api/Project/"
export const baseurlProjectPhase = "http://localhost:5010/api/ProjectPhase/"
export const baseurlProjectTask = "http://localhost:5010/api/ProjectTask/"
